### ISSUE TITLE
get_recent_clips_by_xuid doesn't return latest clips

### ISSUE THREAD

**Issue by Cdingram** [OpenXbox/xbox-webapi-python#23] opened 2020-05-09 19:47 UTC
Apparently xbox changed something mid to late 2019 and most recent clips aren't returned from this api call. [This](https://github.com/XboxReplay/xboxlive-api) project shows this message on the recent clips call: "Warning: Recent games (since mid-2019) will not be returned, please use getPlayerGameClipsFromActivityHistory instead (if required).". Seems like the workaround now is to parse gameclips from the activity feed rather than just the clips API call.

**Comment by Alexis-Bize** [comment] 2020-07-13 09:14
Hey @Cdingram, I'm the author of the shared library.

Even if activity history trick works, used endpoint is rate limited and seems to be unstable. The best workaround is to use "mediahub.xboxlive.com" domain but as far as I know, it requires a valid XSTS token generated via "UserToken / DeviceToken / TitleToken" combination which requires signed requests (see https://github.com/OpenXbox/xbox-webapi-python/tree/task/signed_requests).

**Comment by tuxuser** [comment] 2020-11-13 03:07
If somebody finds a way, please send a PR.
**WONTFIX** as this is an API limitation, not a bug in this library.

**Closed by tuxuser** 2020-11-13 03:07 UTC
Labels: feature, wontfix
